### ISSUE TITLE
NoMethodError: undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by nnzo** [openware/barong#1029]
Hi,
I've been trying to solve this issue for a while now.

Running db:seed in barong causes this error:

```rake aborted!
NoMethodError: undefined method `each' for nil:NilClass
/home/app/lib/barong/seed.rb:46:in `seed_permissions'
/home/app/db/seeds.rb:7:in `<main>'
/home/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/home/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/home/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `block in load'
/home/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `load'
/home/app/vendor/bundle/ruby/2.6.0/gems/railties-5.2.2.1/lib/rails/engine.rb:551:in `load_seed'
/home/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.2.1/lib/active_record/tasks/database_tasks.rb:281:in `load_seed'
/home/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.2.1/lib/active_record/railties/databases.rake:194:in `block (2 levels) in <main>'
Tasks: TOP => db:setup => db:seed
```

If anyone has any ideas on why this could be happening, please let me know :)

**Comment by nnzo** [comment]
There was no permissions in the config file🤦
