### ISSUE TITLE
event_api_jwt_private_key Error 

### ISSUE THREAD

**Issue by knkrth** [openware/barong#888]
```
~/barong$ bundle exec rake db:create db:migrate
W, [2019-08-06T07:14:55.933387 #18065]  WARN -- : Warning !! Generating private key
rake aborted!
Barong::App::Error: Config event_api_jwt_private_key missing
/home/gsrwallet/barong/lib/barong/app.rb:22:in `set'
/home/gsrwallet/barong/config/initializers/event_api.rb:11:in `block in <main>'
/home/gsrwallet/barong/lib/barong/app.rb:11:in `define'
/home/gsrwallet/barong/config/initializers/event_api.rb:9:in `<main>'
/home/gsrwallet/barong/config/environment.rb:5:in `<main>'
/home/gsrwallet/.rbenv/versions/2.6.0/bin/bundle:23:in `load'
/home/gsrwallet/.rbenv/versions/2.6.0/bin/bundle:23:in `<main>'
Tasks: TOP => db:create => db:load_config => environment
(See full trace by running task with --trace)```

**Comment by ec** [comment]
Just set the env `EVENT_API_JWT_PRIVATE_KEY`
its standard behavior, not an error

**Comment by knkrth** [comment]
I did `export event_api_jwt_private_key=secret` Still I got the same error

**Comment by ec** [comment]
@knkrth try to with big letters
```
export small_env=test
export SMALL_ENV=test
```
caused for me 2 different env :
```
small_env=test
SMALL_ENV=test
```

**Comment by knkrth** [comment]
Thanks it worked.
